module Api
  module V1
    class RegistrationsController < Devise::RegistrationsController
      respond_to :json

      skip_before_action :authenticate_user_from_token!, raise: false
      skip_before_action :ensure_company!,               raise: false

      # Pundit: registration is public, no authorization needed
      after_action :skip_authorization

      before_action :configure_permitted_parameters

      def create
        company_name = params.dig(:user, :company_name).presence ||
                       "#{sign_up_params[:first_name]&.strip}'s Company"

        ActiveRecord::Base.transaction do
          @company = Company.create!(
            name: company_name
            # slug auto-generated by Company#generate_slug before_validation
          )

          build_resource(sign_up_params)
          resource.company = @company
          resource.role    = 'owner'   # founding registrant is always owner

          resource.save!

          # Create the canonical membership record
          CompanyMembership.create!(
            user:        resource,
            company:     @company,
            role:        'owner',
            accepted_at: Time.current
          )

          AllocationSetting.create!(
            company:     @company,
            user:        resource,
            salary_pct:  40.0,
            ops_pct:     25.0,
            profit_pct:  35.0
          )
        end

        if resource.persisted?
          # Generate a JWT so the client is logged in immediately after registration
          token, _payload = Warden::JWTAuth::UserEncoder.new.call(resource, :user, nil)

          render json: {
            success: true,
            message: 'Account created successfully',
            token:   token,
            user:    user_payload(resource)
          }, status: :created
        else
          render json: {
            success: false,
            errors:  resource.errors.full_messages
          }, status: :unprocessable_content
        end

      rescue ActiveRecord::RecordInvalid => e
        # Transaction rolled back — report the actual validation errors
        render json: {
          success: false,
          errors:  e.record.errors.full_messages
        }, status: :unprocessable_content
      end

      protected

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [
          :first_name, :last_name, :email,
          :password, :password_confirmation,
          :company_name
        ])
      end

      private

      def user_payload(user)
        {
          id:           user.id,
          email:        user.email,
          first_name:   user.first_name,
          last_name:    user.last_name,
          role:         user.role,
          full_name:    user.full_name,
          avatar:       user.avatar,
          company_id:   user.company_id,
          company_name: user.company&.name
        }
      end
    end
  end
end